---
name: upload
on:
  push:
    branches:
      - 'master'

jobs:
  check:
    runs-on: data
    steps:
      - uses: actions/checkout@v2
      - run: make check

  upload:
    needs: check
    runs-on: data
    env:
      PYPISERVER_URL: ${{ secrets.PYPISERVER_URL }}
    steps:
      - uses: actions/checkout@v2
      - run: make upload

